In [23]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [24]:
race = pd.read_csv("donnees_formule_un/races.csv")

In [25]:
race.replace("\\N", np.nan, inplace=True)

In [26]:
date = ["date", "fp1_date", "fp2_date", "fp3_date", "quali_date", "sprint_date"]
for _ in date:
    race[_] = pd.to_datetime(race[_])

In [27]:
time = ["time","fp1_time", "fp2_time", "fp3_time", "quali_time", "sprint_time"]
for _ in time:
    race[_] = pd.to_timedelta(race[_])

In [28]:
race.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   object
 5   date         1125 non-null   datetime64[ns]
 6   time         394 non-null    timedelta64[ns]
 7   url          1125 non-null   object
 8   fp1_date     90 non-null     datetime64[ns]
 9   fp1_time     68 non-null     timedelta64[ns]
 10  fp2_date     90 non-null     datetime64[ns]
 11  fp2_time     68 non-null     timedelta64[ns]
 12  fp3_date     72 non-null     datetime64[ns]
 13  fp3_time     53 non-null     timedelta64[ns]
 14  quali_date   90 non-null     datetime64[ns]
 15  quali_time   68 non-null     timedelta64[ns]
 16  sprint_date  18 non-null     datetime64[ns]
 17  sprint_time  15 non-null     timedelta64[ns]
dtypes: datetime64[ns](6), int64(4), object(2), timedelta64[ns](6)
memory usage: 158.3+ KB

In [29]:
race

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,0 days 06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,0 days 09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,0 days 07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,0 days 12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,0 days 12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,0 days 20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,0 days 18:30:00,2024-10-25,0 days 22:00:00,2024-10-26,0 days 17:30:00,2024-10-26,0 days 21:00:00,NaT,NaT
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,0 days 17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,0 days 14:30:00,2024-11-01,0 days 18:30:00,NaT,NaT,2024-11-02,0 days 18:00:00,2024-11-02,0 days 14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,0 days 06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,0 days 02:30:00,2024-11-21,0 days 06:00:00,2024-11-22,0 days 02:30:00,2024-11-22,0 days 06:00:00,NaT,NaT
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,0 days 17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,0 days 13:30:00,2024-11-29,0 days 17:30:00,NaT,NaT,2024-11-30,0 days 17:00:00,2024-11-30,0 days 13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,0 days 13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,0 days 09:30:00,2024-12-06,0 days 13:00:00,2024-12-07,0 days 10:30:00,2024-12-07,0 days 14:00:00,NaT,NaT

In [33]:
for _ in time:
    print(_)
    print(race[_].min())
    print(race[_].max())
    print(race[_].mean())
    print(race[_].std())

time
0 days 03:00:00
0 days 20:00:00
0 days 12:27:55.126903553
0 days 03:33:38.817299418
fp1_time
0 days 01:30:00
0 days 19:00:00
0 days 11:32:38.823529411
0 days 04:23:18.717454974
fp2_time
0 days 05:00:00
0 days 22:00:00
0 days 14:26:01.764705882
0 days 04:26:42.994397148
fp3_time
0 days 01:30:00
0 days 19:00:00
0 days 10:39:37.358490566
0 days 04:17:02.793340595
quali_time
0 days 05:00:00
0 days 22:00:00
0 days 14:30:52.941176470
0 days 04:13:49.022475153
sprint_time
0 days 03:00:00
0 days 22:00:00
0 days 14:52:00
0 days 04:25:47.556910968

à quelle heure commence en moyenne les courses par circuit ? 
Est ce que les sprints, les essais (free practice) et les qualif commence de manière identique ? 
On remarque ici 
qu'en moyenne on commence à 14h30 les qualif, 15h les sprints,
mais avec une variance de départ entre 4h13 et 4h25 pour les deux

Idée !!! utiliser une map, localisation géographique 
de chaque course et faire une map colorée des heures de départ des courses à travers le globe

In [51]:
unique_race = list(race["name"].unique())

# Assuming 'time' is a list of column names related to the durations, e.g., ['time_column1', 'time_column2']
for race_name in unique_race:
    race_data = race[race["name"] == race_name]  # Filter DataFrame for each race
    for duration_column in time[1:]:  # Assuming 'time' is a list of column names like ['time1', 'time2']
        print(f"Pour la course {race_name} \n"
              f" la durée min {race_data[duration_column].min()},\n"
              f" la durée max {race_data[duration_column].max()},\n"
              f"la durée moyenne du circuit est de {race_data[duration_column].mean()}\n"
              f"pour un écart-type de {race_data[duration_column].std()}")

Pour la course Australian Grand Prix
 la durée min 0 days 01:30:00,
 la durée max 0 days 03:00:00,
la durée moyenne du circuit est de 0 days 02:00:00
pour un écart-type de 0 days 00:51:57.691453623
Pour la course Australian Grand Prix
 la durée min 0 days 05:00:00,
 la durée max 0 days 06:00:00,
la durée moyenne du circuit est de 0 days 05:20:00
pour un écart-type de 0 days 00:34:38.460969082
Pour la course Australian Grand Prix
 la durée min 0 days 01:30:00,
 la durée max 0 days 03:00:00,
la durée moyenne du circuit est de 0 days 02:00:00
pour un écart-type de 0 days 00:51:57.691453623
Pour la course Australian Grand Prix
 la durée min 0 days 05:00:00,
 la durée max 0 days 06:00:00,
la durée moyenne du circuit est de 0 days 05:20:00
pour un écart-type de 0 days 00:34:38.460969082
Pour la course Australian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Malaysian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Malaysian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Malaysian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Malaysian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Malaysian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Chinese Grand Prix
 la durée min 0 days 03:30:00,
 la durée max 0 days 03:30:00,
la durée moyenne du circuit est de 0 days 03:30:00
pour un écart-type de NaT
Pour la course Chinese Grand Prix
 la durée min 0 days 07:30:00,
 la durée max 0 days 07:30:00,
la durée moyenne du circuit est de 0 days 07:30:00
pour un écart-type de NaT
Pour la course Chinese Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Chinese Grand Prix
 la durée min 0 days 07:00:00,
 la durée max 0 days 07:00:00,
la durée moyenne du circuit est de 0 days 07:00:00
pour un écart-type de NaT
Pour la course Chinese Grand Prix
 la durée min 0 days 03:00:00,
 la durée max 0 days 03:00:00,
la durée moyenne du circuit est de 0 days 03:00:00
pour un écart-type de NaT
Pour la course Bahrain Grand Prix
 la durée min 0 days 11:30:00,
 la durée max 0 days 12:00:00,
la durée moyenne du circuit est de 0 days 11:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Bahrain Grand Prix
 la durée min 0 days 15:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 15:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Bahrain Grand Prix
 la durée min 0 days 11:30:00,
 la durée max 0 days 12:30:00,
la durée moyenne du circuit est de 0 days 12:00:00
pour un écart-type de 0 days 00:30:00
Pour la course Bahrain Grand Prix
 la durée min 0 days 15:00:00,
 la durée max 0 days 16:00:00,
la durée moyenne du circuit est de 0 days 15:20:00
pour un écart-type de 0 days 00:34:38.460969082
Pour la course Bahrain Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Spanish Grand Prix
 la durée min 0 days 11:30:00,
 la durée max 0 days 12:00:00,
la durée moyenne du circuit est de 0 days 11:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Spanish Grand Prix
 la durée min 0 days 15:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 15:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Spanish Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 11:00:00,
la durée moyenne du circuit est de 0 days 10:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Spanish Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 14:00:00,
la durée moyenne du circuit est de 0 days 14:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Spanish Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Monaco Grand Prix
 la durée min 0 days 11:30:00,
 la durée max 0 days 12:00:00,
la durée moyenne du circuit est de 0 days 11:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Monaco Grand Prix
 la durée min 0 days 15:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 15:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Monaco Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 11:00:00,
la durée moyenne du circuit est de 0 days 10:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Monaco Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 14:00:00,
la durée moyenne du circuit est de 0 days 14:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Monaco Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Turkish Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Turkish Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Turkish Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Turkish Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Turkish Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course British Grand Prix
 la durée min 0 days 11:30:00,
 la durée max 0 days 12:00:00,
la durée moyenne du circuit est de 0 days 11:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course British Grand Prix
 la durée min 0 days 15:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 15:00:00
pour un écart-type de 0 days 00:00:00
Pour la course British Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 11:00:00,
la durée moyenne du circuit est de 0 days 10:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course British Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 14:00:00,
la durée moyenne du circuit est de 0 days 14:00:00
pour un écart-type de 0 days 00:00:00
Pour la course British Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course German Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course German Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course German Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course German Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course German Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Hungarian Grand Prix
 la durée min 0 days 11:30:00,
 la durée max 0 days 12:00:00,
la durée moyenne du circuit est de 0 days 11:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Hungarian Grand Prix
 la durée min 0 days 15:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 15:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Hungarian Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 11:00:00,
la durée moyenne du circuit est de 0 days 10:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Hungarian Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 14:00:00,
la durée moyenne du circuit est de 0 days 14:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Hungarian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course European Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course European Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course European Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course European Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course European Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Belgian Grand Prix
 la durée min 0 days 11:30:00,
 la durée max 0 days 12:00:00,
la durée moyenne du circuit est de 0 days 11:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Belgian Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 13:30:00
pour un écart-type de 0 days 02:35:53.074360871
Pour la course Belgian Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 11:00:00,
la durée moyenne du circuit est de 0 days 10:45:00
pour un écart-type de 0 days 00:21:12.792206135
Pour la course Belgian Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 14:20:00
pour un écart-type de 0 days 00:34:38.460969082
Pour la course Belgian Grand Prix
 la durée min 0 days 14:30:00,
 la durée max 0 days 14:30:00,
la durée moyenne du circuit est de 0 days 14:30:00
pour un écart-type de NaT
Pour la course Italian Grand Prix
 la durée min 0 days 11:30:00,
 la durée max 0 days 12:00:00,
la durée moyenne du circuit est de 0 days 11:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Italian Grand Prix
 la durée min 0 days 15:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 15:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Italian Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 11:00:00,
la durée moyenne du circuit est de 0 days 10:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Italian Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 14:00:00,
la durée moyenne du circuit est de 0 days 14:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Italian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Singapore Grand Prix
 la durée min 0 days 09:30:00,
 la durée max 0 days 10:00:00,
la durée moyenne du circuit est de 0 days 09:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Singapore Grand Prix
 la durée min 0 days 13:00:00,
 la durée max 0 days 13:00:00,
la durée moyenne du circuit est de 0 days 13:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Singapore Grand Prix
 la durée min 0 days 09:30:00,
 la durée max 0 days 10:00:00,
la durée moyenne du circuit est de 0 days 09:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Singapore Grand Prix
 la durée min 0 days 13:00:00,
 la durée max 0 days 13:00:00,
la durée moyenne du circuit est de 0 days 13:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Singapore Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Japanese Grand Prix
 la durée min 0 days 02:30:00,
 la durée max 0 days 03:00:00,
la durée moyenne du circuit est de 0 days 02:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Japanese Grand Prix
 la durée min 0 days 06:00:00,
 la durée max 0 days 06:00:00,
la durée moyenne du circuit est de 0 days 06:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Japanese Grand Prix
 la durée min 0 days 02:30:00,
 la durée max 0 days 03:00:00,
la durée moyenne du circuit est de 0 days 02:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Japanese Grand Prix
 la durée min 0 days 06:00:00,
 la durée max 0 days 06:00:00,
la durée moyenne du circuit est de 0 days 06:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Japanese Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Brazilian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Brazilian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Brazilian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Brazilian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Brazilian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Abu Dhabi Grand Prix
 la durée min 0 days 09:30:00,
 la durée max 0 days 10:00:00,
la durée moyenne du circuit est de 0 days 09:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Abu Dhabi Grand Prix
 la durée min 0 days 13:00:00,
 la durée max 0 days 13:00:00,
la durée moyenne du circuit est de 0 days 13:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Abu Dhabi Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 11:00:00,
la durée moyenne du circuit est de 0 days 10:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Abu Dhabi Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 14:00:00,
la durée moyenne du circuit est de 0 days 14:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Abu Dhabi Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Canadian Grand Prix
 la durée min 0 days 17:30:00,
 la durée max 0 days 18:00:00,
la durée moyenne du circuit est de 0 days 17:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Canadian Grand Prix
 la durée min 0 days 21:00:00,
 la durée max 0 days 21:00:00,
la durée moyenne du circuit est de 0 days 21:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Canadian Grand Prix
 la durée min 0 days 16:30:00,
 la durée max 0 days 17:00:00,
la durée moyenne du circuit est de 0 days 16:40:00
pour un écart-type de 0 days 00:17:19.230484541
Pour la course Canadian Grand Prix
 la durée min 0 days 20:00:00,
 la durée max 0 days 20:00:00,
la durée moyenne du circuit est de 0 days 20:00:00
pour un écart-type de 0 days 00:00:00
Pour la course Canadian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course French Grand Prix
 la durée min 0 days 12:00:00,
 la durée max 0 days 12:00:00,
la durée moyenne du circuit est de 0 days 12:00:00
pour un écart-type de NaT
Pour la course French Grand Prix
 la durée min 0 days 15:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 15:00:00
pour un écart-type de NaT
Pour la course French Grand Prix
 la durée min 0 days 11:00:00,
 la durée max 0 days 11:00:00,
la durée moyenne du circuit est de 0 days 11:00:00
pour un écart-type de NaT
Pour la course French Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 14:00:00,
la durée moyenne du circuit est de 0 days 14:00:00
pour un écart-type de NaT
Pour la course French Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course United States Grand Prix
 la durée min 0 days 17:30:00,
 la durée max 0 days 19:00:00,
la durée moyenne du circuit est de 0 days 18:00:00
pour un écart-type de 0 days 00:51:57.691453623
Pour la course United States Grand Prix
 la durée min 0 days 18:00:00,
 la durée max 0 days 22:00:00,
la durée moyenne du circuit est de 0 days 20:30:00
pour un écart-type de 0 days 02:10:46.018098373
Pour la course United States Grand Prix
 la durée min 0 days 19:00:00,
 la durée max 0 days 19:00:00,
la durée moyenne du circuit est de 0 days 19:00:00
pour un écart-type de NaT
Pour la course United States Grand Prix
 la durée min 0 days 21:00:00,
 la durée max 0 days 22:00:00,
la durée moyenne du circuit est de 0 days 21:40:00
pour un écart-type de 0 days 00:34:38.460969082
Pour la course United States Grand Prix
 la durée min 0 days 18:00:00,
 la durée max 0 days 22:00:00,
la durée moyenne du circuit est de 0 days 20:00:00
pour un écart-type de 0 days 02:49:42.337649086
Pour la course San Marino Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course San Marino Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course San Marino Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course San Marino Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course San Marino Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Austrian Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 11:30:00,
la durée moyenne du circuit est de 0 days 11:10:00
pour un écart-type de 0 days 00:34:38.460969082
Pour la course Austrian Grand Prix
 la durée min 0 days 10:30:00,
 la durée max 0 days 14:30:00,
la durée moyenne du circuit est de 0 days 11:50:00
pour un écart-type de 0 days 02:18:33.843876330
Pour la course Austrian Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Austrian Grand Prix
 la durée min 0 days 14:00:00,
 la durée max 0 days 15:00:00,
la durée moyenne du circuit est de 0 days 14:40:00
pour un écart-type de 0 days 00:34:38.460969082
Pour la course Austrian Grand Prix
 la durée min 0 days 10:00:00,
 la durée max 0 days 14:30:00,
la durée moyenne du circuit est de 0 days 13:00:00
pour un écart-type de 0 days 02:35:53.074360871
Pour la course Argentine Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Argentine Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Argentine Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Argentine Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Argentine Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Luxembourg Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Luxembourg Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Luxembourg Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Luxembourg Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT
Pour la course Luxembourg Grand Prix
 la durée min NaT,
 la durée max NaT,
la durée moyenne du circuit est de NaT
pour un écart-type de NaT

In [50]:
race_data

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
1099,1119,2023,21,80,Las Vegas Grand Prix,2023-11-19,0 days 06:00:00,https://en.wikipedia.org/wiki/2023_Las_Vegas_G...,2023-11-16,0 days 04:30:00,2023-11-16,0 days 08:00:00,2023-11-17,0 days 04:30:00,2023-11-17,0 days 08:00:00,NaT,NaT
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,0 days 06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,0 days 02:30:00,2024-11-21,0 days 06:00:00,2024-11-22,0 days 02:30:00,2024-11-22,0 days 06:00:00,NaT,NaT